dist: trusty
sudo: required
services:
- docker
language: cpp

env:
  matrix:
  - IMAGE_ARCH=amd64
  - IMAGE_ARCH=arm64
  - IMAGE_ARCH=armel
  - IMAGE_ARCH=armhf
  - IMAGE_ARCH=i386
  - IMAGE_ARCH=mips
  - IMAGE_ARCH=mips64el
  - IMAGE_ARCH=mipsel
  - IMAGE_ARCH=ppc64el
  - IMAGE_ARCH=s390x
  global:
  - DOCKER_EXEC_ROOT="sudo docker exec -it -u root test_container"
  - DOCKER_EXEC="sudo docker exec -it test_container"

branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+/

addons:
  apt:
    sources:
    - sourceline: 'deb http://archive.ubuntu.com/ubuntu/ devel universe'
    packages:
    - binfmt-support
    - qemu-user-static

cache:
- apt

before_install:
- sudo docker run -d -i -t --name test_container -v ${TRAVIS_BUILD_DIR%${TRAVIS_REPO_SLUG}}:${TRAVIS_BUILD_DIR%${TRAVIS_REPO_SLUG}} laarid/devel:${IMAGE_ARCH} /bin/bash

install:
- ${DOCKER_EXEC_ROOT} apt-get update -qq
- ${DOCKER_EXEC_ROOT} mk-build-deps -i -s sudo -t 'apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends -y' ${TRAVIS_BUILD_DIR}/debian/control

script:
- ${DOCKER_EXEC} /bin/sh -c "cd ${TRAVIS_BUILD_DIR}; debuild --preserve-env --preserve-envvar PATH -i -us -uc -b"
