language: cpp

cache:
- apt
- ccache

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

install:
- sudo apt-get install -qq devscripts equivs gcc-4.8 g++-4.8
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
- mk-build-deps -i -s sudo

script:
- env
- debuild --preserve-env --preserve-envvar PATH -i -us -uc -b

deploy:
  provider: releases
  api-key:
    secure: hb5ks+djqhJ7RqVyt0JiQvJv3o6YWFhPq+C7ZNnmJcZm1Rn64VyEW4GUIIWa4cSxJzZCHQfIpigV5HUrn5Y3hjYgYc15vow2p/zNdI/EUIJjjQ2t765dEAKJKhXsRlnEncczMMHaigrtbGUUn3byhXNGKmKqDuNdwJiHbSdQgoU=
  file:
  - $TRAVIS_BUILD_DIR/../libbionic0_0.1.0_amd64.deb
  - $TRAVIS_BUILD_DIR/../libbionic0-dev_0.1.0_amd64.deb
  skip_cleanup: true
  on:
    tags: true
