language: cpp

cache:
- apt
- ccache

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

install:
- sudo apt-get install -qq devscripts equivs gcc-4.8 g++-4.8
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
- mk-build-deps -i -s sudo

script:
- env
- debuild --preserve-env --preserve-envvar PATH -i -us -uc -b
